# Generated by Django 4.1.7 on 2023-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.CharField(max_length=64)),
                ('preoo', models.IntegerField()),
            ],
        ),
    ]
