# Generated by Django 4.1.7 on 2023-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=64)),
                ('compras', models.ManyToManyField(blank=True, related_name='marcas', to='compras.compras')),
            ],
        ),
    ]
